### PR TITLE
Add requried steps to setup Intel SGX device plugin in Minikube

### PR DESCRIPTION
**Pull request by Nirusu**
And here I thought Kubernetes + SGX was actually easy with Minikube... Oh boy, a couple of hours down the road just to write this down.

Can someone please check if actually *all* these steps are required to setup the device plugin? Intel's site says something about "prebuilt Docker images", though for my taste that's still way too many steps to get this running.

Oh, any the site also says something about "remove `kConfig` from `nfd-worker.conf` when running <Kernel 5.11...? Honestly, the whole documentation on how to set this up is a mess.

So, if there are any improvements or this can be WAY more easy with Minikube, please tell me... This was quite a disaster to get to when you are unfamiliar with this stuff.

### CODE REVIEW

**Comment by Nirusu** [comment]
Actually, giving it a second thought... Shouldn't we be able to integrate this into our CLI tool? Would definitely help quite a bit and would be a way more seamless experience.

**Comment by daniel-weisse** [comment]
Can't really test this at the moment, as i dont have a machine with the newest SGX drivers installed, but Intel provides a solution with a smaller deployment footprint, which uses the prebuilt docker images mentioned at the start of the docs: https://intel.github.io/intel-device-plugins-for-kubernetes/cmd/sgx_plugin/README.html#deploy-the-daemonset

We can run the device plugin installation with a single command:
```bash
kubectl apply -k https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/sgx_plugin/overlays/epc-register/?ref=main
```

I also have a memory of reading about an intel CLI tool to install their device plugins, however I might be confusing it with their [plugins operator](https://github.com/intel/intel-device-plugins-for-kubernetes#device-plugins-operator).

**Comment by Nirusu** [comment]
While this does indeed seem to install the device plugin, it appears to not be functioning quite correctly on my machine. The Coordinator fails to launch as it cannot load the SGX device. When manually going through all the steps, it works fine.

It's quite a bummer, I would love this to be a "one command" solution instead of these confusing lines of commands...

**Comment by daniel-weisse** [comment]
Fixed by https://github.com/edgelesssys/emojivoto/pull/32

**Pull request closed without merging**
