### PR TITLE
Feat/ttls

### PR DESCRIPTION
**Pull request by m1ghtym0**

### CODE REVIEW

**Comment by m1ghtym0** [comment]
I get the following error in the `web` service when running this version:
```
[ego] starting application ...
2021/07/19 08:20:57 Connecting to [voting-svc.emojivoto:8080]
2021/07/19 08:20:57 Connecting to [emoji-svc.emojivoto:8080]
2021/07/19 08:20:57 Starting web server on WEB_PORT=[4433]
2021/07/19 08:20:57 Error serving request [&{GET /api/vote?choice=:doughnut: HTTP/1.1 1 1 map[Accept-Encoding:[gzip] User-Agent:[Go-http-client/1.1] X-B3-Sampled:[1] X-B3-Spanid:[96b203a43567428c] X-B3-Traceid:[6ea6b8f2778ec57fa67940581ee6a3b7]] {} <nil> 0 [] false web-svc:443 map[choice:[:doughnut:]] map[] <nil> map[] 10.240.0.92:46036 /api/vote?choice=:doughnut: <nil> <nil> <nil> 0x7f331807d6e0}]: rpc error: code = Unknown desc = ERROR
2021/07/19 08:20:59 Error serving request [&{GET /api/vote?choice=:doughnut: HTTP/1.1 1 1 map[Accept-Encoding:[gzip] User-Agent:[Go-http-client/1.1] X-B3-Sampled:[1] X-B3-Spanid:[6ac14206c3f60636] X-B3-Traceid:[a74212060e8c793af1ffeb59e0a15f95]] {} <nil> 0 [] false web-svc:443 map[choice:[:doughnut:]] map[] <nil> map[] 10.240.0.92:46042 /api/vote?choice=:doughnut: <nil> <nil> <nil> 0x7f33184b4870}]: rpc error: code = Unknown desc = ERROR
panic: accept tcp [::]:4433: accept4: protocol error

goroutine 1 [running]:
github.com/edgelesssys/emojivoto/emojivoto-web/web.StartServerNoTLS(0x7f3318024029, 0x4, 0x0, 0x0, 0x7f331802606d, 0x20, 0x7f3301a27d40, 0x7f33180be5d8, 0x7f3301a37338, 0x7f33180be5a0)
        /emojivoto/emojivoto-web/web/web.go:454 +0x97c
main.main()
        /emojivoto/emojivoto-web/cmd/server.go:83 +0x5d2
```

You can try using image version `v0.4.1` in `kubernetes/sgx_values.yaml`.
The error only seems to happen when connecting via Browser. vote-bot seems fine.

**Comment by 3u13r** [comment]
The version you mentioned works fine in Chrome, Firefox, and Edge but I see the same crash in IE. I assume that you observed the error on one of the first three browser. Which one? Which version? 
Will fix the issue with IE though, hopefully the bug is the same.

**Comment by m1ghtym0** [comment]
Was using Chrome Version 91.0.4472.124

**Comment by 3u13r** [comment]
I checked, this is the same chrome version I tested it with. Could you maybe also add the error that Chrome showed and which setup you used? I imagine that you deployed it in AKS? I tested it in minikube locally. Those differences maybe cause Chrome to behave differently. 

We are currently changing the error handling more generally and I think that this will fix this issue.

**Comment by m1ghtym0** [comment]
The error occurs only occasionally:
image
Sometimes you get `ERR_CONNECTION_CLOSED`
image

**Comment by m1ghtym0** [comment]
Retested, with the correct images based on the latest EGo image.
Issue is fixed, thanks!

**Comment by 3u13r** [comment]
lgtm

**Review by 3u13r — APPROVED** [review]
lgtm

**Pull request merged**
